import { ACTION_BY_ID } from '@unintended/world-data';
import { ACTION_CATEGORY, resolveSemanticInput } from '../commands/parser.js';
import type { CommandResult, EntityView, GameEvent, GameRepository } from '../model.js';
import { helpLine } from '../systems/help.js';

const ev=(type:GameEvent['type'],actorId:string,targetId?:string,locationId?:string,payload?:Record<string,unknown>):GameEvent=>({type,actorId,targetId,locationId,payload,at:new Date()});
const pick=<T>(items:readonly T[]):T=>items[Math.floor(Math.random()*items.length)]!;
const normalise=(value:string)=>value.trim().toLowerCase().replace(/[?.!,]+$/g,'').replace(/\s+/g,' ');
const isDiscoverable=(verb:string)=>verb==='INQUIRE'||ACTION_BY_ID.get(verb)?.discoverable===true;
const questionSignature=(kind:string,scope:string,subject:string,specificity:number)=>`${kind}:${scope}:${normalise(subject)}:${Math.floor(specificity*4)}`;

function similarity(a:string,b:string){const left=normalise(a).replace(/[^a-z0-9]/g,''),right=normalise(b).replace(/[^a-z0-9]/g,'');if(!left||!right)return 0;if(left===right)return 1;if(left.includes(right)||right.includes(left))return Math.min(left.length,right.length)/Math.max(left.length,right.length);const shared=new Set([...left].filter(char=>right.includes(char))).size;return shared/Math.max(left.length,right.length);}
function proximityLines(category:string|undefined,distinct:number,verb:string){if(distinct<=1)return [pick([`That belongs suspiciously close to ${category??'something real'}.`,`The Server has filed that under ${category??'UNDECIDED'} provisionally.`,`You are not correct. You are, regrettably, adjacent to correct.`])];if(distinct===2)return [`You have described ${category??'the same idea'} in more than one defensible way.`,`The world appears to use a narrower word than you do.`];return ['The Server is tired of pretending you have not understood the idea.',`CONCEPT INFERRED: ${verb}`];}
function failureHint(action:string,count:number){if(count<=1)return null;if(count===2)return `The same ${action.toLowerCase()} problem has now occurred twice. This is evidence, not progress.`;if(count===3)return `Repeating the action is unlikely to alter the missing condition. Change the target, state, or context.`;return `The Server has stopped counting this as experimentation. Find new evidence before trying ${action} again.`;}
function readableContent(target:EntityView){const name=normalise(target.name);if(name.includes('letter'))return ['LETTER','',target.held?'The letter is in your possession.':'The letter is within reach.','The visible text reads:','"Registry Clerk: the bearer has the item. The Registry still lists it elsewhere."','','That seems less like correspondence and more like an accusation with stationery.'];if(name.includes('ledger'))return ['LEDGER','','Three columns are legible:','POSSESSED BY / RECORDED OWNER / EXPECTED LOCATION','','Several entries disagree. The ledger does not appear embarrassed.'];if(name.includes('sign'))return ['SIGN','','PROPERTY OF THE REGISTRY','','Someone has crossed out PROPERTY and written PROBABLY.'];return [target.name.toUpperCase(),'','There is something to read here, but nothing currently meaningful has been authored for it. The Server considers this an administrative failure.'];}
function worldInquiry(scope:string,kind:string,subject:string,locationName:string){
 if(scope==='SELF')return kind==='LOCATE'?[`You are currently in ${locationName}.`,`This answers where. It does not answer why.`]:['You are here because you entered. Motive remains your department.','Your immediate purpose is less philosophical: establish what Bellweather thinks belongs to whom, then find where the record disagrees.'];
 if(scope==='TITLE')return ['Your title is the Server’s current estimate of demonstrated understanding.','It is not a level. It is also not a compliment, even when it sounds like one.'];
 if(scope==='ACTION')return [`${subject.toUpperCase()} is a recognised concept if you have actually demonstrated it.`,`Typing a word and understanding a rule are no longer considered equivalent.`];
 return ['Bellweather has a local ownership problem.','Objects, possession, and the Registry do not entirely agree with one another.','Establish the disagreement well enough that the boundary considers you competent to leave.'];
}
function inquiryResponse(subject:EntityView|undefined,specificity:number,questionKind:string,repetition:number){
 if(!subject)return ['The question is understandable. The requested subject is not currently supported by your evidence.'];
 const facts=subject.facts?.length?subject.facts:[`${subject.name} is here.`],penalty=1/(1+Math.max(0,repetition-1)*.9),usefulChance=Math.max(.08,Math.min(.82,.24+specificity*.5)*penalty),roll=Math.random();
 if(roll<usefulChance)return [pick(facts)];
 const output=[pick([`${subject.name} has survived another inquiry.`,`The Server has reviewed your question about ${subject.name}.`,`You are asking about something real. This is an improvement.`])];
 if(repetition>=2)output.push('Repeating the same question is reducing the useful-answer budget.');if(repetition>=3)output.push('Ask about a relationship, purpose, possession, destination, or event instead.');if(questionKind==='CAUSE'&&subject.kind==='NPC')output.push(`${subject.name} may know more if you ask about something specific rather than existence in general.`);return output;
}

export class GameEngine{
 constructor(private repo:GameRepository){}
 async execute(playerId:string,raw:string):Promise<CommandResult>{
  const actor=await this.repo.getActor(playerId),semantic=resolveSemanticInput(raw,actor.knownConcepts),events:GameEvent[]=[],lines:string[]=[];const meta={kind:semantic.kind,verb:semantic.verb,category:semantic.category,confidence:semantic.confidence};if(!semantic.verb)return {lines:['You do nothing with remarkable precision.'],events,semantic:meta};
  if(semantic.kind==='PROXIMITY'){
   const surface=semantic.matchedSurface??semantic.surfaceVerb??semantic.raw,probe=await this.repo.registerSemanticProbe(playerId,semantic.verb,surface);events.push(ev('PLAYER_PROBED_CONCEPT',playerId,undefined,actor.locationId,{concept:semantic.verb,surface,distinct:probe.distinct,category:semantic.category}));lines.push(...proximityLines(semantic.category,probe.distinct,semantic.verb));let discoveredConcept:string|undefined;if(probe.distinct>=3&&isDiscoverable(semantic.verb)&&await this.repo.discoverConcept(playerId,semantic.verb)){discoveredConcept=semantic.verb;events.push(ev('PLAYER_DISCOVERED_CONCEPT',playerId,undefined,actor.locationId,{concept:semantic.verb,category:semantic.category,inferred:true}));}await this.repo.recordEvents(events);return {lines,events,discoveredConcept,semantic:meta};
  }
  if(semantic.kind==='INQUIRY'){
   const scope=semantic.questionScope??'ENTITY',locationName=await this.repo.getLocationName(actor.locationId),subjectText=semantic.subject?.trim()??'',specificity=semantic.specificity??.4,kind=semantic.questionKind??'DESCRIBE',signature=questionSignature(kind,scope,subjectText,specificity),repetition=await this.repo.registerInquiry(playerId,signature);
   if(scope!=='ENTITY')lines.push(...worldInquiry(scope,kind,subjectText,locationName));else{const accessible=await this.repo.listAccessibleEntities(playerId);let subject=accessible.find(entity=>normalise(entity.name)===normalise(subjectText))??accessible.find(entity=>normalise(subjectText).includes(normalise(entity.name))||normalise(entity.name).includes(normalise(subjectText)));if(!subject&&subjectText){const ranked=accessible.map(entity=>({entity,score:similarity(subjectText,entity.name)})).sort((a,b)=>b.score-a.score);if(ranked[0]?.score>=.55)subject=ranked[0].entity;}lines.push(...inquiryResponse(subject,specificity,kind,repetition));if(subject?.kind==='NPC'&&/registry|letter|ledger|owner|own|possession/i.test(raw))lines.push(`${subject.name} appears noticeably more relevant when ownership or records are mentioned.`);events.push(ev('PLAYER_ASKED_QUESTION',playerId,subject?.id,actor.locationId,{signature,repetition,specificity,questionKind:kind,scope}));}
   return this.finish(playerId,actor.locationId,'INQUIRE',lines,events,true,`inquiry:${scope}:${kind}:${normalise(subjectText)}`,meta);
  }
  if(semantic.kind==='UNKNOWN')return {lines:[pick(['The Server understands that you intended something. It cannot yet bind the wording to a safe action.','That sentence has intent. The current grammar model has failed to prove which intent.','Your wording is plausible human language. This has unfortunately not narrowed matters enough.'])],events,semantic:meta};

  const cmd=semantic;
  if(cmd.verb==='HELP'){lines.push(helpLine(Date.now()));return this.finish(playerId,actor.locationId,'HELP',lines,events,true,'help',meta);}
  if(cmd.verb==='INVENTORY'){const accessible=await this.repo.listAccessibleEntities(playerId),held=accessible.filter(entity=>entity.held);if(!held.length)lines.push('You are carrying nothing the Server is prepared to list.');else{lines.push('IN YOUR POSSESSION','');for(const item of held)lines.push(item.name);}return this.finish(playerId,actor.locationId,'INVENTORY',lines,events,true,'inventory',meta);}
  if(cmd.verb==='LOOK'){
   const here=await this.repo.getLocationName(actor.locationId),entities=await this.repo.listPlayerLocationEntities(playerId),exits=await this.repo.listLocationExits(actor.locationId);let success=true;if(cmd.args.length){const query=cmd.args.join(' '),target=await this.repo.findAccessibleEntity(playerId,query);if(target){lines.push(target.name.toUpperCase(),'');lines.push(...(target.facts??[`${target.name} is here.`]));}else{lines.push(`You look for ${query}. Nothing in the room or your possession answers.`);success=false;}}else{lines.push(here.toUpperCase(),'');if(!entities.length)lines.push('There is nothing obvious here.');else for(const entity of entities)lines.push(`${entity.name} is here.`);if(exits.length){lines.push('','Ways that seem to leave:');for(const exit of exits)lines.push(`${exit.shape}  ${exit.label}`);}if(actor.locationId==='bellweather-square')lines.push('','Something in Bellweather disagrees about ownership. The Registry would prefer you prove it before making accusations.');}events.push(ev('PLAYER_LOOKED',playerId,undefined,actor.locationId,{exitKeys:exits.map(exit=>exit.directionKey)}));return this.finish(playerId,actor.locationId,'LOOK',lines,events,success,`look:${cmd.args.join(' ')||'room'}`,meta);
  }
  if(cmd.verb==='MOVE'||cmd.verb==='LEAVE'||cmd.verb==='JUMP'){
   if(!cmd.args.length){const count=await this.repo.registerFailure(playerId,'movement:no-destination');lines.push('Movement requires a destination, route, or remembered relationship.');const hint=failureHint('MOVE',count);if(hint)lines.push(hint);return {lines,events,semantic:meta};}const destination=cmd.args.join(' '),moved=await this.repo.movePlayer(playerId,destination);if(!moved){const count=await this.repo.registerFailure(playerId,`movement:${normalise(destination)}`);lines.push(pick(['There is no valid route matching that wording from here.','The destination is understandable. The route is not currently valid.','This location does not connect to that request.']));const hint=failureHint('MOVE',count);if(hint)lines.push(hint);return {lines,events,semantic:meta};}lines.push(`You move to ${moved.toName}.`);events.push(ev('PLAYER_MOVED',playerId,undefined,moved.to,{from:moved.from,directionKey:moved.directionKey,action:cmd.verb}));return this.finish(playerId,moved.to,cmd.verb,lines,events,true,`move:${moved.directionKey??moved.to}`,meta);
  }
  if(cmd.verb==='TAKE'){
   const query=cmd.args.join(' '),target=await this.repo.findPlayerVisibleEntity(playerId,query);if(!target){const count=await this.repo.registerFailure(playerId,`take:${normalise(query)}`);lines.push('There is no matching unattended thing here to take.');const hint=failureHint('TAKE',count);if(hint)lines.push(hint);return {lines,events,semantic:meta};}if(!target.portable){lines.push(`The ${target.name} does not look conveniently portable. Exceptions have existed.`);return {lines,events,semantic:meta};}const success=await this.repo.takeItem(playerId,target.id);if(success){lines.push(`You take the ${target.name}.`);events.push(ev('ITEM_TAKEN',playerId,target.id,actor.locationId));}else lines.push('That did not become yours. Ownership has retained legal counsel.');return this.finish(playerId,actor.locationId,'TAKE',lines,events,success,`take:${target.id}`,meta);
  }
  if(cmd.verb==='DROP'){const dropped=await this.repo.dropItem(playerId,cmd.args.join(' '));if(dropped){lines.push(`You drop the ${dropped.name}.`);events.push(ev('ITEM_DROPPED',playerId,dropped.id,actor.locationId));return this.finish(playerId,actor.locationId,'DROP',lines,events,true,`drop:${dropped.id}`,meta);}const count=await this.repo.registerFailure(playerId,`drop:${normalise(cmd.args.join(' '))}`);lines.push('You are not currently holding that.');const hint=failureHint('DROP',count);if(hint)lines.push(hint);return {lines,events,semantic:meta};}
  if(cmd.verb==='OPEN'){const query=cmd.args.join(' '),target=await this.repo.findAccessibleEntity(playerId,query);if(!target){lines.push('There is nothing accessible by that name.');return {lines,events,semantic:meta};}if(!target.openable){lines.push(`The ${target.name} does not appear to participate in opening. This is not necessarily a permanent moral position.`);return {lines,events,semantic:meta};}const success=await this.repo.openEntity(playerId,target.id);if(success){lines.push(`You open the ${target.name}.`);events.push(ev('DOOR_OPENED',playerId,target.id,actor.locationId));}else lines.push(`You cannot currently open the ${target.name}. It may already have made that decision.`);return this.finish(playerId,actor.locationId,'OPEN',lines,events,success,`open:${target.id}`,meta);}
  if(cmd.verb==='READ'){const query=cmd.args.join(' '),target=await this.repo.findAccessibleEntity(playerId,query);if(target){lines.push(...readableContent(target));return this.finish(playerId,actor.locationId,'READ',lines,events,true,`read:${target.id}`,meta);}const count=await this.repo.registerFailure(playerId,`read:${normalise(query)}`);lines.push('Nothing accessible matches that reading target.');const hint=failureHint('READ',count);if(hint)lines.push(hint);return {lines,events,semantic:meta};}

  const directional=await this.repo.movePlayer(playerId,cmd.raw);if(directional){lines.push(`You move to ${directional.toName}.`);events.push(ev('PLAYER_MOVED',playerId,undefined,directional.to,{from:directional.from,directionKey:directional.directionKey,bareDirection:true}));return this.finish(playerId,directional.to,'MOVE',lines,events,true,`move:${directional.directionKey??directional.to}`,meta);}
  const action=ACTION_BY_ID.get(cmd.verb);if(action){const targetText=cmd.args.join(' ');let success=false;if(['PERCEPTION','KNOWLEDGE'].includes(action.category)&&targetText){const target=await this.repo.findAccessibleEntity(playerId,targetText);if(target){lines.push(target.name.toUpperCase(),'');lines.push(...(target.facts??[`${target.name} is accessible.`]));success=true;}else lines.push(`The Server understands the ${cmd.verb} intent, but no accessible target satisfies it.`);}else if(action.category==='SOCIAL'&&targetText){const target=await this.repo.findPlayerVisibleEntity(playerId,targetText);if(target?.kind==='NPC'){lines.push(`${target.name} acknowledges you. If you want information, ask about something specific.`);success=true;}else lines.push('The social intent is clear. The intended participant is not.');}else lines.push(`The Server recognises ${cmd.verb}, but this build does not yet have a valid world-state transition for it here.`);if(success)return this.finish(playerId,actor.locationId,cmd.verb,lines,events,true,`${cmd.verb.toLowerCase()}:${normalise(targetText)||'context'}`,meta);const count=await this.repo.registerFailure(playerId,`${cmd.verb}:${normalise(targetText)||'context'}`),hint=failureHint(cmd.verb,count);if(hint)lines.push(hint);return {lines,events,semantic:meta};}
  return {lines:['The world has no safe interpretation for that yet.'],events,semantic:meta};
 }

 private async finish(playerId:string,locationId:string,verb:string,lines:string[],events:GameEvent[],success:boolean,contextKey:string,semantic:CommandResult['semantic']):Promise<CommandResult>{
  let discoveredConcept:string|undefined;if(success&&isDiscoverable(verb)&&await this.repo.discoverConcept(playerId,verb)){discoveredConcept=verb;events.push(ev('PLAYER_DISCOVERED_CONCEPT',playerId,undefined,locationId,{concept:verb,category:ACTION_CATEGORY[verb]}));lines.push('',`CONCEPT DISCOVERED: ${verb}`);}const anomaly=await this.repo.tryDesignedAnomalies(events,playerId);if(anomaly.claimed){lines.push('','ANOMALY RETAINED',anomaly.claimed.name??'','Something in that sequence should have resolved differently.','The exception is yours now. The Server objects to this arrangement.');events.push(ev('PLAYER_DISCOVERED_ANOMALY',playerId,anomaly.claimed.id,locationId,{retained:anomaly.retained}));}const understanding=await this.repo.recordUnderstanding(playerId,verb,contextKey,success,{anomaly:!!anomaly.claimed});if(understanding.tierChanged){lines.push('','TITLE REVISED',understanding.currentTitle,'The Server has updated its estimate of your competence. It appears irritated by the result.');events.push(ev('TITLE_CHANGED',playerId,undefined,locationId,{title:understanding.currentTitle}));}await this.repo.recordEvents(events);return {lines,events,discoveredConcept,semantic};
 }
}
