import { useEffect,useRef,useState } from 'react';
type Line={id:number,text:string,kind?:'system'|'input'};
export function App(){const [player,setPlayer]=useState<any>(null);const [lines,setLines]=useState<Line[]>([]);const [input,setInput]=useState('');const ws=useRef<WebSocket|null>(null);const scrollRef=useRef<HTMLDivElement>(null);
 const append=(texts:string[],kind?:Line['kind'])=>setLines(v=>[...v,...texts.map((text,i)=>({id:Date.now()+i+Math.random(),text,kind}))].slice(-400));
 async function refresh(){const r=await fetch('/api/me',{credentials:'include'});if(r.ok)setPlayer((await r.json()).player);}
 async function devLogin(slot=1){const r=await fetch(`/api/dev/login/${slot}`,{method:'POST',credentials:'include'});if(r.ok){setPlayer((await r.json()).player);}}
 useEffect(()=>{refresh()},[]);useEffect(()=>{if(!player)return;const proto=location.protocol==='https:'?'wss':'ws';const socket=new WebSocket(`${proto}://${location.host}/ws`);ws.current=socket;socket.onopen=()=>append(['CONNECTED.','']);socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='OUTPUT')append(m.lines);else if(m.text)append([m.text],'system');};socket.onclose=()=>append(['DISCONNECTED.'],'system');return()=>socket.close();},[player]);useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[lines]);
 function submit(e:React.FormEvent){e.preventDefault();const text=input.trim();if(!text||ws.current?.readyState!==WebSocket.OPEN)return;append([`> ${text}`],'input');ws.current.send(JSON.stringify({type:'COMMAND',text}));setInput('');}
 if(!player)return <main className="shell"><section className="gate"><h1>UNINTENDED</h1><p>No tutorial.<br/>No starter bonus.<br/>No chosen one.</p><p>You wanted to be here.</p><button onClick={()=>devLogin(1)}>ENTER</button><small>Development self-test identity</small></section></main>;
 return <main className="shell"><section className="terminal" aria-label="game terminal"><header><strong>UNINTENDED</strong><span>{player.name}</span></header><div className="scroll">{lines.length===0&&<div className="opening">BELLWEATHER<br/><br/>Possibly.<br/><br/></div>}{lines.map(l=><div key={l.id} className={l.kind??''}>{l.text||' '}</div>)}<div ref={end}/></div><form onSubmit={submit}><label>&gt;</label><input autoFocus autoComplete="off" spellCheck={false} value={input} onChange={e=>setInput(e.target.value)} maxLength={240}/></form></section></main>}
