import { useEffect, useMemo, useRef, useState } from 'react';

type Line={id:number;text:string;kind?:'system'|'input'};
type Direction={key:string;shape:string;label:string};
type MemoryNode={id:string;name:string|null;x:number;y:number;status:'visited'|'inferred';current:boolean};
type MemoryEdge={from:string;to:string;directionKey:string;shape:string;label:string;status:'known'|'inferred'};
type Memory={rememberedDirectionCount:number;nodes:MemoryNode[];edges:MemoryEdge[];directions:Direction[]};
type PlayerState={id:string;name:string;locationId:string};
type DiscoveredAction={id:string;category:string};
type RegionGoal={id:string;label:string;complete:boolean;progress:number;target:number};
type Reward={kind:string;key:string;label:string};
type Progression={title:string;currentRegion:string;assessment:string;goal:string;goals:RegionGoal[];hint:string|null;rewards:Reward[];nextRegions:Array<{directionKey:string;shape:string;label:string;regionId:string}>};
type Anomaly={id:string;name:string;domain:string;apparentUtility:string};
type SocialMap={id:string;name:string;facet:string;code:string};
type SocialLink={from:string;to:string;source:'seed'|'world'};
type Social={origin:SocialMap;maps:SocialMap[];links:SocialLink[];linkedMapCount:number;totalMapCount:number;scope:string;assignmentLines:string[]};
type Relationship={npcId:string;npcName:string;level:string;established:boolean;needsAttention:boolean;maintenanceTask:string|null};
type Thread={id:string;title:string;detail:string;state:'OPEN'|'WATCHING'|'COOLING'};

function label(value:string){return value.toLowerCase().replace(/_/g,' ').replace(/\b\w/g,char=>char.toUpperCase());}
function MemoryField({memory}:{memory:Memory|null}){if(!memory||!memory.nodes.length)return <div className="memory-empty">Nothing has become memorable yet.</div>;const nodeById=new Map(memory.nodes.map(node=>[node.id,node])),xs=memory.nodes.map(node=>node.x),ys=memory.nodes.map(node=>node.y),minX=Math.min(...xs)-1,maxX=Math.max(...xs)+1,minY=Math.min(...ys)-1,maxY=Math.max(...ys)+1,scale=34,width=Math.max(170,(maxX-minX)*scale),height=Math.max(170,(maxY-minY)*scale),point=(node:MemoryNode)=>({x:(node.x-minX)*scale,y:(node.y-minY)*scale});return <><div className="memory-map"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Discovered world memory">{memory.edges.map(edge=>{const from=nodeById.get(edge.from),to=nodeById.get(edge.to);if(!from||!to)return null;const a=point(from),b=point(to);return <g key={`${edge.from}-${edge.directionKey}-${edge.to}`} className={`memory-edge ${edge.status}`}><line x1={a.x} y1={a.y} x2={b.x} y2={b.y}/><text x={(a.x+b.x)/2} y={(a.y+b.y)/2-4}>{edge.shape}</text></g>;})}{memory.nodes.map(node=>{const p=point(node);return <g key={node.id} className={`memory-node ${node.status} ${node.current?'current':''}`}><rect x={p.x-4} y={p.y-4} width="8" height="8"/>{node.current&&<circle cx={p.x} cy={p.y} r="8"/>}{node.name&&<text className="place-label" x={p.x+8} y={p.y-7}>{node.name}</text>}</g>;})}</svg></div><div className="direction-meta">{memory.rememberedDirectionCount?`${memory.rememberedDirectionCount} directional ${memory.rememberedDirectionCount===1?'tendency':'tendencies'} remembered.`:'No directional vocabulary has survived observation yet.'}</div><div className="direction-list">{memory.directions.map(direction=><div className="direction" key={direction.key}><span>{direction.shape}</span><b>{direction.label}</b></div>)}</div></>}
function SocialMapField({social}:{social:Social|null}){if(!social)return <div className="region-empty">No social geography has admitted responsibility for you.</div>;const maps=social.maps.slice(0,9),visible=new Set(maps.map(map=>map.id)),size=210,cx=105,cy=100,radius=70,points=new Map(maps.map((map,index)=>{const angle=(Math.PI*2*index/Math.max(1,maps.length))-Math.PI/2;return [map.id,{x:cx+Math.cos(angle)*radius,y:cy+Math.sin(angle)*radius}]}));return <><div className="social-summary"><b>{social.origin.name}</b><span>{social.scope} REACH · {social.maps.length}/{social.totalMapCount} MAPS</span></div><div className="social-map"><svg viewBox={`0 0 ${size} ${size}`} role="img" aria-label="Connected social maps">{social.links.filter(link=>visible.has(link.from)&&visible.has(link.to)).map(link=>{const a=points.get(link.from),b=points.get(link.to);if(!a||!b)return null;return <line key={`${link.from}-${link.to}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className={link.source==='world'?'world-link':''}/>})}{maps.map(map=>{const p=points.get(map.id)!;const origin=map.id===social.origin.id;return <g key={map.id} className={`social-node ${origin?'origin':''}`}><circle cx={p.x} cy={p.y} r={origin?7:5}/><text x={p.x} y={p.y+16}>{map.code}</text></g>})}</svg></div><div className="social-map-names">{maps.map(map=><span key={map.id} className={map.id===social.origin.id?'origin':''}>{map.name}</span>)}</div></>}
function RegionCondition({progression,anomalies}:{progression:Progression|null;anomalies:Anomaly[]}){if(!progression)return <div className="region-empty">The Server has misplaced your regional assessment.</div>;return <div className="region-condition"><div className={`assessment ${progression.assessment.toLowerCase()}`}>{progression.assessment}</div><h2>{label(progression.currentRegion)}</h2><p className="condition-copy">{progression.goal}</p><div className="goal-list">{progression.goals.map(goal=><div className={`goal-row ${goal.complete?'done':''}`} key={goal.id}><span>{goal.complete?'◆':'◇'}</span><div><b>{goal.label}</b>{goal.target>0&&<small>{goal.progress}/{goal.target}</small>}</div></div>)}</div>{progression.hint&&<div className="threshold-hint">{progression.hint}</div>}{progression.rewards.length>0&&<><h3>RETAINED BENEFITS</h3><div className="reward-list">{progression.rewards.slice(-5).map(reward=><div key={`${reward.kind}:${reward.key}`}><b>{label(reward.kind)}</b><span>{reward.label}</span></div>)}</div></>}{anomalies.length>0&&<><h3>RETAINED EXCEPTIONS</h3><div className="anomaly-list">{anomalies.slice(-5).map(anomaly=><div key={anomaly.id}><span>◈</span><div><b>{anomaly.name}</b><small>{anomaly.domain} · {label(anomaly.apparentUtility)}</small></div></div>)}</div></>}</div>}
function ThreadList({threads}:{threads:Thread[]}){return <div className="thread-list">{threads.length?threads.map(thread=><div className={`thread ${thread.state.toLowerCase()}`} key={thread.id}><span>{thread.state==='OPEN'?'◇':thread.state==='COOLING'?'◌':'·'}</span><div><b>{thread.title}</b><small>{thread.detail}</small></div></div>):<div className="region-empty compact">Nothing unresolved is currently admitting it.</div>}</div>}
function RelationshipList({relationships}:{relationships:Relationship[]}){return <div className="relationship-list">{relationships.length?relationships.slice(0,6).map(person=><div className="relationship" key={person.npcId}><div><b>{person.npcName}</b><span>{label(person.level)}</span></div>{person.needsAttention&&person.maintenanceTask&&<small>{person.maintenanceTask}</small>}{person.established&&!person.needsAttention&&<small>History is currently doing enough of the remembering.</small>}</div>):<div className="region-empty compact">Nobody currently has enough history with you to be interesting.</div>}</div>}

export function App(){
 const [player,setPlayer]=useState<PlayerState|null>(null),[memory,setMemory]=useState<Memory|null>(null),[actionCategories,setActionCategories]=useState<string[]>([]),[discoveredActions,setDiscoveredActions]=useState<DiscoveredAction[]>([]),[progression,setProgression]=useState<Progression|null>(null),[anomalies,setAnomalies]=useState<Anomaly[]>([]),[social,setSocial]=useState<Social|null>(null),[relationships,setRelationships]=useState<Relationship[]>([]),[threads,setThreads]=useState<Thread[]>([]),[activeCategory,setActiveCategory]=useState('PERCEPTION'),[lines,setLines]=useState<Line[]>([]),[input,setInput]=useState('');const ws=useRef<WebSocket|null>(null),scrollRef=useRef<HTMLDivElement>(null);
 const append=(texts:string[],kind?:Line['kind'])=>setLines(current=>[...current,...texts.map((text,index)=>({id:Date.now()+index+Math.random(),text,kind}))].slice(-500));
 async function refreshState(){const response=await fetch('/api/me',{credentials:'include'});if(!response.ok)return false;const data=await response.json();setPlayer(data.player);setMemory(data.memory??null);setActionCategories(Array.isArray(data.actionCategories)?data.actionCategories.map(String):[]);setDiscoveredActions(Array.isArray(data.discoveredActions)?data.discoveredActions:[]);setProgression(data.progression??null);setAnomalies(Array.isArray(data.anomalies)?data.anomalies:[]);setSocial(data.social??null);setRelationships(Array.isArray(data.relationships)?data.relationships:[]);setThreads(Array.isArray(data.threads)?data.threads:[]);
  if(data.player?.id&&data.social?.origin?.id){const key=`origin-seen:${data.player.id}:${data.social.origin.id}`;if(!localStorage.getItem(key)){append(['',...(data.social.assignmentLines??[]),''],'system');localStorage.setItem(key,'1');}}
  if(data.player?.id&&Array.isArray(data.returnRecap)&&data.returnRecap.length){const key=`recap:${data.player.id}:${data.returnRecap.join('|')}`;if(!sessionStorage.getItem(key)){append(['','WHILE YOU WERE ABSENT',...data.returnRecap,''],'system');sessionStorage.setItem(key,'1');}}
  return true;}
 async function devLogin(slot=1){const response=await fetch(`/api/dev/login/${slot}`,{method:'POST',credentials:'include'});if(response.ok){await refreshState();return;}append(['THE SERVER FAILED TO LET YOU IN.'],'system');}
 useEffect(()=>{void refreshState();},[]);useEffect(()=>{if(!player?.id)return;const proto=location.protocol==='https:'?'wss':'ws',socket=new WebSocket(`${proto}://${location.host}/ws`);ws.current=socket;socket.onopen=()=>append(['CONNECTED.','']);socket.onmessage=event=>{const message=JSON.parse(event.data);if(message.type==='OUTPUT'&&Array.isArray(message.lines)){append(message.lines.map(String));void refreshState();}else if(message.text)append([String(message.text)],'system');};socket.onclose=()=>append(['DISCONNECTED.'],'system');return()=>{ws.current=null;socket.close();};},[player?.id]);useEffect(()=>{const el=scrollRef.current;if(el)el.scrollTop=el.scrollHeight;},[lines]);useEffect(()=>{if(actionCategories.length&&!actionCategories.includes(activeCategory))setActiveCategory(actionCategories[0]!);},[actionCategories,activeCategory]);
 const categories=useMemo(()=>actionCategories.map(id=>({id,label:label(id),count:discoveredActions.filter(action=>action.category===id).length})),[actionCategories,discoveredActions]),discoveredInActive=useMemo(()=>discoveredActions.filter(action=>action.category===activeCategory),[discoveredActions,activeCategory]);
 function submit(event:React.FormEvent){event.preventDefault();const text=input.trim();if(!text||ws.current?.readyState!==WebSocket.OPEN)return;append([`> ${text}`],'input');ws.current.send(JSON.stringify({type:'COMMAND',text}));setInput('');}
 if(!player)return <main className="shell"><section className="gate"><h1>UNINTENDED</h1><p>No tutorial.<br/>No starter bonus.<br/>No chosen one.</p><p>Something is wrong here.<br/>The Server considers this normal.</p><button onClick={()=>devLogin(1)}>ENTER</button><small>Development self-test identity</small></section></main>;
 return <main className="shell"><div className="game-layout"><aside className="side-panel lexicon" aria-label="Discovered actions"><header><strong>DISCOVERED</strong><span>actions</span></header><nav className="category-tabs">{categories.map(category=><button key={category.id} className={category.id===activeCategory?'active':''} onClick={()=>setActiveCategory(category.id)}><span>{category.label}</span><b>{category.count}</b></button>)}</nav><section className="action-list"><h2>{label(activeCategory).toUpperCase()}</h2>{discoveredInActive.length?discoveredInActive.map(action=><div className="action-chip" key={action.id}>{action.id}</div>):<p>None understood.</p>}<small>{discoveredInActive.length?`${discoveredInActive.length} understood.`:'The category remains annoyingly plausible.'}</small></section></aside><section className="terminal" aria-label="game terminal"><header><strong>UNINTENDED</strong><span className="identity"><b>{player.name}</b>{progression?.title&&<small>{progression.title}</small>}</span></header><div className="scroll" ref={scrollRef}>{lines.length===0&&<div className="opening">BELLWEATHER<br/><br/>The Registry says certain things belong to people who do not appear to have them.<br/>Other people have things the Registry says are elsewhere.<br/><br/>Establish which version of ownership is lying.<br/><br/>The Server will allow you to leave when your understanding is sufficiently inconvenient.</div>}{lines.map(line=><div key={line.id} className={line.kind??''}>{line.text||'\u00a0'}</div>)}</div><form onSubmit={submit}><label>&gt;</label><input autoFocus autoComplete="off" spellCheck={false} value={input} onChange={event=>setInput(event.target.value)} maxLength={240}/></form></section><aside className="side-panel world-panel" aria-label="World understanding"><header><strong>WORLD CONDITION</strong><span>assessment</span></header><div className="world-scroll"><div className="section-title"><strong>OPEN THREADS</strong><span>{threads.length}</span></div><ThreadList threads={threads}/><RegionCondition progression={progression} anomalies={anomalies}/><div className="memory-divider"><strong>MEMORY FIELD</strong><span>personal evidence</span></div><MemoryField memory={memory}/><div className="memory-divider"><strong>SOCIAL MAP</strong><span>reachable world</span></div><SocialMapField social={social}/><div className="memory-divider"><strong>KNOWN PEOPLE</strong><span>relationships decay</span></div><RelationshipList relationships={relationships}/></div></aside></div></main>;
}
