import { mapIdentityForMapId } from './map-identities.js';

export type MapStateBand='STABLE'|'FRAYED'|'ACTIVE';
export type MapVersion={
  id:string;designation:string;surfacePressure:string;privateTwist:string;echoId:string;
  questLead:string;curiosityLead:string;foreignArchetypes:string[];
  approaches:[string,string,string];consequences:[string,string,string];
  stateBands:Record<MapStateBand,string>;
};

type VersionSeed=Omit<MapVersion,'id'>;

const V:Record<string,VersionSeed[]>={
 'possession-registry':[
  {designation:'The Duplicate Deed',surfacePressure:'Two households can each prove ownership of the same ordinary property.',privateTwist:'The original deed is absent in every local record but referenced by two foreign institutions.',echoId:'FIRST-CORRECTION',questLead:'A Registrar wants an external witness to explain which copy was recognised first.',curiosityLead:'A courier route sometimes produces an envelope bearing a Registry seal from another Map.',foreignArchetypes:['identity-roll','unremembered-archive'],approaches:['Trace documentary provenance','Change physical possession and observe institutional reaction','Use witnesses to make the Registry choose'],consequences:['One household loses legal access without losing the object','A witness becomes part of the ownership record','A foreign record becomes locally authoritative'],stateBands:{STABLE:'The duplicate ownership is treated as an administrative nuisance.',FRAYED:'Ordinary services begin obeying different owners.',ACTIVE:'The property itself starts behaving as though both claims are valid.'}},
  {designation:'The Owner Who Never Arrived',surfacePressure:'Property is assigned to a person nobody has met.',privateTwist:'The absent owner matches a recognised identity elsewhere but not under the same name.',echoId:'MISSING-WITNESS',questLead:'The Clerk requests evidence that the owner exists outside this jurisdiction.',curiosityLead:'Trying to address mail to the owner creates inconsistent route suggestions.',foreignArchetypes:['identity-roll','returning-roads'],approaches:['Find a matching identity elsewhere','Test whether someone can inherit the claim','Invalidate the address rather than the owner'],consequences:['Ownership migrates to a witness','The address becomes more authoritative than the person','A route begins treating the absent owner as a destination'],stateBands:{STABLE:'The owner is merely absent.',FRAYED:'Bills and deliveries continue to recognise them.',ACTIVE:'Local systems begin reserving space for a person who is not present.'}},
  {designation:'Possession by Receipt',surfacePressure:'A receipt is being treated as stronger evidence than possession.',privateTwist:'The receipt predates the transfer it supposedly proves.',echoId:'BORROWED-AUTHORITY',questLead:'Market Arbitration wants the receipt compared with foreign transaction rules.',curiosityLead:'Destroying or hiding copies changes who NPCs accuse but not who the Registry recognises.',foreignArchetypes:['prior-market','surviving-debts'],approaches:['Attack the receipt chronology','Transfer the object repeatedly','Follow the obligation attached to the purchase'],consequences:['Debt and ownership split','A buyer becomes responsible without becoming owner','The record survives destruction through another institution'],stateBands:{STABLE:'The receipt is unusual evidence.',FRAYED:'Services begin favouring the receipt holder.',ACTIVE:'Possession changes fail to alter recorded ownership at all.'}},
  {designation:'The Property That Returned',surfacePressure:'An item keeps returning to a recorded location after legitimate transfers.',privateTwist:'Its old location corresponds to a route definition preserved on another Map.',echoId:'UNFINISHED-RETURN',questLead:'The Registry asks Surveyors why an address behaves like ownership.',curiosityLead:'Dropping the item near certain routes changes where it reappears.',foreignArchetypes:['returning-roads','unremembered-archive'],approaches:['Break the route/address relationship','Change the record rather than the object','Establish a new witnessed resting place'],consequences:['A room inherits ownership-like behaviour','The object becomes a route marker','A historic address resurfaces in current records'],stateBands:{STABLE:'The item occasionally returns.',FRAYED:'Transfers become temporary.',ACTIVE:'The location itself starts reclaiming unrelated property.'}}
 ],
 'identity-roll':[
  {designation:'The Double Witness',surfacePressure:'Two residents are recognised as the same person by different institutions.',privateTwist:'Both identities descend from one correction record that no Map admits authoring.',echoId:'FIRST-CORRECTION',questLead:'Witness House wants an external record that distinguishes the residents.',curiosityLead:'Introducing either resident under the other name changes unrelated NPC responses.',foreignArchetypes:['possession-registry','unremembered-archive'],approaches:['Separate them through contradictory witnesses','Make one identity acquire incompatible property','Find an event only one can remember'],consequences:['An institution splits while another merges them harder','Property history becomes identity evidence','A witness loses confidence in their own records'],stateBands:{STABLE:'The duplication is bureaucratic.',FRAYED:'Services begin sharing consequences between them.',ACTIVE:'Actions by one can alter the other’s recognised history.'}},
  {designation:'The Name With No Resident',surfacePressure:'A valid identity has documents, obligations and mail but no body.',privateTwist:'A route elsewhere recognises the name as a destination.',echoId:'MISSING-WITNESS',questLead:'The Registrar asks another Map to confirm whether the person ever arrived.',curiosityLead:'Speaking the name in different locations produces inconsistent social recognition.',foreignArchetypes:['returning-roads','surviving-debts'],approaches:['Follow the obligations','Follow the destination','Give the identity a new witness'],consequences:['A player becomes a legal witness to nobody','A debt gains a usable addressee','A route starts generating presence evidence'],stateBands:{STABLE:'The identity exists only on paper.',FRAYED:'NPCs begin recalling interactions with it.',ACTIVE:'The world starts reserving consequences for the absent person.'}},
  {designation:'The Borrowed Signature',surfacePressure:'Different people can temporarily authenticate as one recognised resident.',privateTwist:'The signature is treated as transferable property by another culture.',echoId:'BORROWED-AUTHORITY',questLead:'Identity staff want the signature compared with ownership law elsewhere.',curiosityLead:'Signing mundane records can make social familiarity attach to the wrong person.',foreignArchetypes:['possession-registry','prior-market'],approaches:['Treat the signature as property','Create incompatible signed actions','Find who bears the consequences of a borrowed identity'],consequences:['Reputation transfers without memory','A transaction recognises the signer but not the person','The signature develops custody history'],stateBands:{STABLE:'The signature is merely over-trusted.',FRAYED:'Institutional actions follow it between people.',ACTIVE:'Personal consequences begin following the signature itself.'}},
  {designation:'The Person Returning Under Another Name',surfacePressure:'Someone comes back from a journey recognised as a different legal person.',privateTwist:'Their route crossed a historic identity boundary preserved in foreign records.',echoId:'UNFINISHED-RETURN',questLead:'The Roll wants a Survey comparison before choosing which identity to retain.',curiosityLead:'Retracing only part of the journey causes NPCs to alternate names.',foreignArchetypes:['returning-roads','unremembered-archive'],approaches:['Reconstruct the route','Reconstruct the remembered identity','Force institutions to process both identities simultaneously'],consequences:['A route acquires identity effects','Old relationships attach unevenly','The Archive records both returns as separate events'],stateBands:{STABLE:'The returnee is disputed.',FRAYED:'Different districts use different identities.',ACTIVE:'The person’s recognised identity changes with movement.'}}
 ],
 'prior-market':[
  {designation:'The Sale That Corrected Itself',surfacePressure:'A completed transaction repeatedly rewrites who paid whom.',privateTwist:'The first correction appears in Registry and Archive records before the sale.',echoId:'FIRST-CORRECTION',questLead:'The Exchange wants external copies of the transaction history.',curiosityLead:'Buying or refusing trivial items changes which version of the old sale is displayed.',foreignArchetypes:['possession-registry','unremembered-archive'],approaches:['Lock one version through ownership','Create a contradictory witness trail','Refuse a predicted consequence'],consequences:['Debt changes sides','Ownership stays while payment history changes','A corrected record becomes older than the transaction'],stateBands:{STABLE:'The sale has multiple histories.',FRAYED:'Balances change depending on which record is consulted.',ACTIVE:'Future trades inherit contradictions from the old sale.'}},
  {designation:'The Customer Who Has Not Arrived',surfacePressure:'A future customer already has receipts and debt.',privateTwist:'Identity and route systems elsewhere both recognise fragments of the customer.',echoId:'MISSING-WITNESS',questLead:'A broker wants confirmation from any Map that can prove the customer exists.',curiosityLead:'Attempting to fulfil the order early changes the customer’s supposed arrival route.',foreignArchetypes:['identity-roll','returning-roads'],approaches:['Fulfil the trade early','Invalidate the customer','Change the route of arrival'],consequences:['The seller inherits the debt','The customer becomes more real through evidence','The order survives cancellation'],stateBands:{STABLE:'The future order is tolerated.',FRAYED:'Inventory begins reserving itself.',ACTIVE:'Goods and prices respond to the absent customer.'}},
  {designation:'Currency on Loan From Tomorrow',surfacePressure:'Some coins are accepted only because records say they will exist later.',privateTwist:'Their legitimacy depends on an authority borrowed from another Map.',echoId:'BORROWED-AUTHORITY',questLead:'Ledger House seeks the institution that first recognised the future currency.',curiosityLead:'Spending the same denomination in different contexts yields different obligation traces.',foreignArchetypes:['surviving-debts','possession-registry'],approaches:['Spend and trace liability','Refuse the currency publicly','Transfer custody without spending it'],consequences:['Debt replaces value','Ownership of the coin matters more than denomination','The currency becomes valid through repeated refusal'],stateBands:{STABLE:'The coins are suspicious tender.',FRAYED:'Prices diverge by payment history.',ACTIVE:'Transactions create value and debt in different orders.'}},
  {designation:'The Delivery That Keeps Finishing',surfacePressure:'A delivery is marked complete every time it returns to the same route.',privateTwist:'The route and obligation disagree about what counts as arrival.',echoId:'UNFINISHED-RETURN',questLead:'Couriers want a Surveyor and Arbiter to compare completion rules.',curiosityLead:'Carrying unrelated parcels through the route sometimes inherits the old delivery status.',foreignArchetypes:['returning-roads','surviving-debts'],approaches:['Change destination','Change recipient obligation','Prove completion through a foreign witness'],consequences:['Parcels inherit old debt','A road becomes part of a contract','Completion creates another delivery'],stateBands:{STABLE:'One delivery is impossible to close.',FRAYED:'Other parcels begin copying its status.',ACTIVE:'The route itself starts issuing completion records.'}}
 ],
 'returning-roads':[
  {designation:'The Corrected Bridge',surfacePressure:'The bridge has two certified geometries and both work.',privateTwist:'Both surveys were accepted during the same unexplained correction event.',echoId:'FIRST-CORRECTION',questLead:'Surveyors want Registry and Archive evidence for which geometry existed first.',curiosityLead:'Carrying records from different institutions changes which route description is repeatable.',foreignArchetypes:['possession-registry','unremembered-archive'],approaches:['Stabilise one survey','Use both routes deliberately','Change which evidence the bridge is carrying'],consequences:['A route becomes institution-dependent','A location gains two valid histories','Travel evidence becomes property'],stateBands:{STABLE:'Both routes are usable.',FRAYED:'Return paths depend on carried evidence.',ACTIVE:'The bridge exposes different local worlds by route choice.'}},
  {designation:'The Destination Without a Traveller',surfacePressure:'A destination receives evidence of arrivals nobody made.',privateTwist:'The arrivals correspond to a recognised absent identity elsewhere.',echoId:'MISSING-WITNESS',questLead:'The Survey Office asks the Roll whether a route can deliver a person who does not exist locally.',curiosityLead:'Waiting at the destination changes logs even without movement.',foreignArchetypes:['identity-roll','unremembered-archive'],approaches:['Observe without travelling','Create a witness at both ends','Redirect the route to a recognised person'],consequences:['Presence becomes route evidence','A witness gains travel history they never performed','The destination begins recognising an absent resident'],stateBands:{STABLE:'Arrival records are unexplained.',FRAYED:'NPCs remember seeing travellers who did not arrive.',ACTIVE:'Destinations begin generating traveller identities.'}},
  {designation:'Right of Way',surfacePressure:'A road only works for whoever is currently recognised as having authority over it.',privateTwist:'Route access behaves like transferable property.',echoId:'BORROWED-AUTHORITY',questLead:'Bridge Wardens seek ownership law that explains why roads accept custody.',curiosityLead:'Lending ordinary items near the road sometimes changes who it permits to pass.',foreignArchetypes:['possession-registry','surviving-debts'],approaches:['Transfer route authority','Contest ownership of the road','Use obligation instead of ownership'],consequences:['Travel privilege becomes debt','The road acquires custody history','A non-owner can become responsible for passage'],stateBands:{STABLE:'Access is merely inconsistent.',FRAYED:'Ownership disputes alter navigation.',ACTIVE:'The road chooses travellers based on social or legal history.'}},
  {designation:'The Return That Never Completed',surfacePressure:'A return journey repeatedly reaches the origin without being considered complete.',privateTwist:'Another institution records a remaining obligation attached to the journey.',echoId:'UNFINISHED-RETURN',questLead:'Surveyors ask the Office of Debts what a route still owes.',curiosityLead:'Dropping carried items mid-route changes which part of the journey remains unfinished.',foreignArchetypes:['surviving-debts','prior-market'],approaches:['Settle the attached obligation','Change what is carried','Redefine origin through witness evidence'],consequences:['A journey becomes inheritable','An object retains unfinished movement','The origin stops recognising return'],stateBands:{STABLE:'The traveller is home but route state remains open.',FRAYED:'Other journeys inherit the unfinished state.',ACTIVE:'The origin itself behaves like a destination still owed an arrival.'}}
 ],
 'unremembered-archive':[
  {designation:'The Record After Correction',surfacePressure:'Every copy of one incident contains edits nobody remembers making.',privateTwist:'The edits correspond to rule changes recorded differently across all six cultures.',echoId:'FIRST-CORRECTION',questLead:'Archivists seek foreign versions of the same incident.',curiosityLead:'Reading copies in different orders changes which contradiction feels oldest.',foreignArchetypes:['possession-registry','identity-roll','prior-market','returning-roads','surviving-debts'],approaches:['Compare foreign versions','Create a fresh witness record','Remove one copy and observe what memory loses'],consequences:['Memory follows the edited version','A deleted record survives as social testimony','Another Map’s version becomes locally older'],stateBands:{STABLE:'The edits are a scholarly problem.',FRAYED:'Witness memories begin aligning with different copies.',ACTIVE:'Reading or moving records changes remembered chronology.'}},
  {designation:'The Missing Witness Catalogue',surfacePressure:'The Archive indexes testimony from witnesses nobody can identify.',privateTwist:'Each missing witness maps to a person, destination or obligation elsewhere.',echoId:'MISSING-WITNESS',questLead:'Archivists want outside confirmation for any listed witness.',curiosityLead:'Searching catalogue numbers as names produces inconsistent social and route responses.',foreignArchetypes:['identity-roll','returning-roads','surviving-debts'],approaches:['Find a matching person','Find a matching route','Find what obligation the witness supposedly observed'],consequences:['A catalogue entry gains identity','A route becomes testimony','A debt becomes proof that someone existed'],stateBands:{STABLE:'The witnesses are merely untraceable.',FRAYED:'NPCs begin remembering some entries.',ACTIVE:'Catalogue entries start participating in current events.'}},
  {designation:'Authority by Citation',surfacePressure:'Repeatedly cited records gain institutional power despite uncertain origin.',privateTwist:'The citations borrow legitimacy from institutions in other Maps.',echoId:'BORROWED-AUTHORITY',questLead:'The Archive wants to know which foreign institution is lending authority.',curiosityLead:'Citing records to unrelated NPCs changes which facts they treat as settled.',foreignArchetypes:['possession-registry','prior-market'],approaches:['Break the citation chain','Over-cite a contradiction','Replace institutional authority with witnesses'],consequences:['A false record becomes operationally true','An institution loses confidence in its own archive','Witnesses become more authoritative than documents'],stateBands:{STABLE:'Citation mostly affects bureaucracy.',FRAYED:'Rules begin following the most cited version.',ACTIVE:'Reality starts privileging documentary consensus.'}},
  {designation:'The Event Still Returning',surfacePressure:'An old incident keeps appearing as newly recorded history.',privateTwist:'Its recurrence follows a route/obligation loop preserved elsewhere.',echoId:'UNFINISHED-RETURN',questLead:'Chronologists seek the route and debt attached to the recurring incident.',curiosityLead:'Visiting locations in unusual orders changes where the next record appears.',foreignArchetypes:['returning-roads','surviving-debts'],approaches:['Break the route loop','Settle the obligation','Create a new ending record'],consequences:['History acquires a destination','An obligation becomes chronological','A new witness can move the recurrence elsewhere'],stateBands:{STABLE:'The incident is periodically re-filed.',FRAYED:'Current events inherit pieces of the old record.',ACTIVE:'The Map behaves as if the incident is happening again.'}}
 ],
 'surviving-debts':[
  {designation:'The Debt Corrected Into Existence',surfacePressure:'An obligation appears only after records are reconciled.',privateTwist:'The same correction event created different liabilities in other Maps.',echoId:'FIRST-CORRECTION',questLead:'The Office seeks foreign records showing what was corrected and who benefited.',curiosityLead:'Settling small unrelated debts changes which historic party appears responsible.',foreignArchetypes:['possession-registry','prior-market','unremembered-archive'],approaches:['Trace benefit instead of debtor','Undo the correction evidence','Transfer responsibility without transferring value'],consequences:['A witness inherits liability','A record becomes a creditor','Settlement reveals another older obligation'],stateBands:{STABLE:'The debt is disputed.',FRAYED:'Institutions begin enforcing different versions.',ACTIVE:'Responsibility attaches to whoever resolves contradictions.'}},
  {designation:'Estate of Nobody',surfacePressure:'An estate persists without a recognised deceased or heir.',privateTwist:'The supposed owner exists only as an identity/route trace elsewhere.',echoId:'MISSING-WITNESS',questLead:'Arbiters want another Map to identify the person the estate belongs to.',curiosityLead:'Taking responsibility for trivial estate property causes unrelated records to address the player as heir.',foreignArchetypes:['identity-roll','returning-roads'],approaches:['Identify an owner','Identify an heir','Prove the estate predates the person'],consequences:['Inheritance creates identity','A route becomes an heir pathway','The estate gains obligations before ownership'],stateBands:{STABLE:'The estate is legally awkward.',FRAYED:'Assets and duties seek an owner independently.',ACTIVE:'The estate begins assigning roles to people who interact with it.'}},
  {designation:'The Obligation That Owns Things',surfacePressure:'A debt can hold property in its own name.',privateTwist:'Its authority is borrowed from ownership and market systems elsewhere.',echoId:'BORROWED-AUTHORITY',questLead:'Arbiters request foreign rulings on whether an obligation can own assets.',curiosityLead:'Giving items to debtors sometimes transfers them to the debt instead.',foreignArchetypes:['possession-registry','prior-market'],approaches:['Challenge ownership capacity','Settle the debt with its own property','Transfer the obligation'],consequences:['Property becomes responsible for itself','Debt survives settlement through ownership','A creditor loses control while remaining beneficiary'],stateBands:{STABLE:'A few assets are misassigned.',FRAYED:'The obligation begins accumulating property.',ACTIVE:'Custody changes can strengthen the debt rather than reduce it.'}},
  {designation:'The Promise Still Travelling',surfacePressure:'A fulfilled promise remains active because one route says delivery never ended.',privateTwist:'The obligation is bound to an unfinished return state.',echoId:'UNFINISHED-RETURN',questLead:'The Office wants Survey evidence for where the promise is still travelling.',curiosityLead:'Walking the route while carrying substitutes changes who the promise considers responsible.',foreignArchetypes:['returning-roads','prior-market'],approaches:['Complete the route differently','Substitute the obligated object','Transfer responsibility to a willing witness'],consequences:['Travel becomes contractual','A substitute inherits history','Completion creates a new beneficiary'],stateBands:{STABLE:'The promise is technically unresolved.',FRAYED:'Other obligations begin sharing its route logic.',ACTIVE:'Movement itself creates or transfers responsibility.'}}
 ]
};

function mapNumber(mapId:string){const n=Number(mapId.replace(/\D+/g,''));return Number.isFinite(n)&&n>0?n:1;}
export function mapVersionForMapId(mapId:string):MapVersion{
  const identity=mapIdentityForMapId(mapId),versions=V[identity.archetypeId]??V['possession-registry']!;
  const index=Math.floor((mapNumber(mapId)-1)/6)%4;
  const seed=versions[index]??versions[0]!;
  return {...seed,id:`${identity.archetypeId}:v${index+1}`};
}

export function mapVersionCount(){return Object.values(V).reduce((n,versions)=>n+versions.length,0);}
export function mapCultureVersionCounts(){return Object.fromEntries(Object.entries(V).map(([key,versions])=>[key,versions.length]));}
export function sharedEchoForMap(mapId:string){const version=mapVersionForMapId(mapId);return {echoId:version.echoId,foreignArchetypes:[...version.foreignArchetypes]};}
